name: Daily build and run

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch: {}
env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup packages
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Restore data cache
        uses: actions/cache/restore@v4
        with:
          key: datastore-${{ runner.os }}
          path: data

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run BMW IX
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
        run: pnpm start IX

      - name: Ensure out exists
        run: mkdir -p out

      - name: Upload out artifacts
        uses: actions/upload-artifact@v4
        with:
          name: out-files
          path: out/**

      - name: Save datastore cache
        uses: actions/cache/save@v4
        with:
          key: datastore-${{ runner.os }}
          path: data
