name: Daily build and run
permissions:
  pages: write
  id-token: write
  contents: write
  actions: write # require to delete cache
on:
  schedule:
    - cron: '45 12 * * *'
  workflow_dispatch: {}
env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup packages
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Restore datastore cache
        id: restore-data-cache
        uses: actions/cache/restore@v4
        with:
          key: datastore-${{ runner.os }}
          path: data

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run
        env:
          BBUSERID: ${{ secrets.BBUSERID }}
          BBPASSWORD: ${{ secrets.BBPASSWORD }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
        run: pnpm start I20

      - name: Ensure out exists
        run: mkdir -p out

      - name: Upload out artifacts
        uses: actions/upload-artifact@v4
        with:
          name: out-files
          path: out/**

      - name: Clear stale datastore cache
        if: ${{ steps.restore-data-cache.outputs.cache-hit }}
        continue-on-error: true
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "datastore-${{ runner.os }}" --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save updated datastore cache
        uses: actions/cache/save@v4
        with:
          key: datastore-${{ runner.os }}
          path: data

      - name: Setup Pages
        if: ${{ hashFiles('out/gh-pages/new.html') != '' }}
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: ${{ hashFiles('out/gh-pages/new.html') != '' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'out/gh-pages'

      - name: Deploy to GitHub Pages
        if: ${{ hashFiles('out/gh-pages/new.html') != '' }}
        id: deployment
        uses: actions/deploy-pages@v4
